Реализовать классы пользователей и вещей в памяти приложения
soursager/java-shareit pull request #1
Opened 2023-12-26 17:41 UTC by soursager

2023-12-27 19:20 UTC, Fleaman777 requested changes

2023-12-27 19:20 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +            ArrayList<Item> itemsForUser = new ArrayList<>();
чуть правильней делать тип более широким, те List, что бы itemsForUser переменная была чуть универсальней

2023-12-27 19:20 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +    private final UserStorage userStorage;
по хорошему, dao/repository/storage классы не должны быть зависимы на другие сторедж классы, они должны отвечать только за взаимодействием с какой-то одной сущностью, по сути иметь зависимость только на конкретное хранилище(юзера, айтемы), тем самым будет соблюдаться принцип разделения ответсвенности,
такой класс будет легче поддерживать, тестрировать, расширять

2023-12-27 19:20 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +    private final Map<Long, List<Item>> items = new HashMap<>();
сложноватая структура, за которой потом тянется работа с ней, итерация, внутри итераций (см getItemById) 
можно было бы сделать ее чуть проще 
    private final Map<Long, Item> items;
    а информация про польхователя у нас есть в Item в поле owner

2023-12-27 19:20 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    @ResponseBody
можно не ставить эту аннотация, тк по сути она уже используется внутри в @RestController

2023-12-27 19:20 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private static final String OWNER = "X-Sharer-User-Id";
хороший вынос в константу

2023-12-27 19:20 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +public class ItemService {
не хватает интерфейса для сервиса 
аналогично для юзера

2023-12-31 13:41 UTC, soursager commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +            ArrayList<Item> itemsForUser = new ArrayList<>();
Расширил, но убрал эту реализацию, т.к. переделывал логику,спасибо!

2023-12-31 13:43 UTC, soursager commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +    private final UserStorage userStorage;
Исправил логику приложения и вынес проверку пользователя на уровень сервиса.

2023-12-31 13:43 UTC, soursager commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +    private final Map<Long, List<Item>> items = new HashMap<>();
Изменил логику приложения.

2023-12-31 13:44 UTC, soursager commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    @ResponseBody
Спасибо, учту!

2023-12-31 13:44 UTC, soursager commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +public class ItemService {
Изменил логику и добавил дополнительный интерфейс для сервиса

2024-01-01 19:59 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +    private final UserStorage userStorage;
отлично, все правильно сделал

2024-01-01 20:00 UTC, Fleaman777 approved these changes

2024-01-17 16:50 UTC, merged