Добавить функцию бронирования
soursager/java-shareit pull request #2
Opened 2024-01-25 20:48 UTC by soursager

2024-01-27 08:17 UTC, Fleaman777 requested changes

2024-01-27 08:17 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +             "where b.item.id = :itemId AND b.booker.id = :bookerId AND b.end <= :now")
что бы запросы чуть лучше воспринимались, можно придерживаться стиля когда ключевые слова типа SELECT, FROM и пр были в верхнем регистре, а названия полей, таблиц в нижнем

2024-01-27 08:17 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        }
блок switch больше создан для применения со строковыми или Енам значениями, когда выбор не будет ограничен 2 значениями, 
с булеан все же хорошо подойдет обычный if else

2024-01-27 08:17 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                || bookingDto.getStart().isBefore(LocalDateTime.now())) {
достаточно большое условие, которое хорошо было бы вынести в отдельный метод с подходящим названием

2024-01-27 08:17 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                UserMapper.toUser(userFromDb))));
а здесь немаленькая вложенность, можно было бы ее разделить, например результат метода save вынести в отдельную локальную переменную, 

с глубокой вложенностью ухудшается восприятие, а так же в какой-то степени дебаггинг

2024-01-27 08:17 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    public BookingDto approveBooking(Long bookingId, Long ownerId, String approve) {
метод изменяет состоние БД, небходимо его выполнить в транзакции 

аналогично в других местах

2024-01-27 08:17 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            case "WAITING": {
вот здесь отличное применение switch

2024-01-27 08:17 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        }
отличный foreach что бы написать его через stream

2024-01-27 08:17 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +            }
немного сложный в понимаю if 
попробуй некоторую часть вынести в отдельный вспомогательный метод

2024-01-27 13:35 UTC, soursager commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +             "where b.item.id = :itemId AND b.booker.id = :bookerId AND b.end <= :now")
Изменил регистры

2024-01-27 13:36 UTC, soursager commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        }
Хотел привить у себя использование switch, но не нужно перебарщивать)

2024-01-27 13:37 UTC, soursager commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                || bookingDto.getStart().isBefore(LocalDateTime.now())) {
Добавил данное условие в отдельный метод

2024-01-27 13:37 UTC, soursager commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                UserMapper.toUser(userFromDb))));
Изменил немного вложенность и создал переменную

2024-01-27 13:37 UTC, soursager commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    public BookingDto approveBooking(Long bookingId, Long ownerId, String approve) {
Поставил аннотации транзакций и транзакций(только чтение)

2024-01-27 13:38 UTC, soursager commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            case "WAITING": {
Спасибо)

2024-01-27 13:38 UTC, soursager commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        }
Спасибо!

2024-01-27 13:38 UTC, soursager commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +            }
Создал дополнительный метод проверки

2024-01-28 13:17 UTC, Fleaman777 approved these changes

2024-02-05 19:44 UTC, merged