Добавить возможность запроса вещи
soursager/java-shareit pull request #3
Opened 2024-03-02 09:22 UTC by soursager

Добавил возможность запроса вещи.
Добавил валидирование в отдельные классы, т.к. это мешало инъекции при тестах и по-моему так лучше, нет повторения.
Добавил новую таблицу.

2024-03-03 20:35 UTC, Fleaman777 requested changes

2024-03-03 20:35 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/validator/BookingValidator.java
> +public class BookingValidator {
хорошая идея вынести валидацию в отдельный компонент, так удобней и тестировать ирасширять валидацию

но я бы может немного поменял название, например на BookingValidatorService
тем самым подчеркнул, что здесь будет не просто статическая валидация, а именно с зависимостью на БД

анаоагично в других подобных местах

2024-03-03 20:35 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/validator/BookingValidator.java
> +    public BookingDto validateAndReturnsBookingDto(long bookingId) {
validateAndReturnBookingDto - будет чуть лучше, 
но на самом деле return можно опустить, потому что из сигнатуры метода это будет вполне понятно

2024-03-03 20:35 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/validator/BookingValidator.java
> +                        " не существует!"));
общая логика, которую можно было бы вынести в отдельный метод

2024-03-03 20:35 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    PageValidator pageableValidator;
в тестах так же хорошо придерживаться принципа инкапсуляции и делать поля private

2024-03-03 20:35 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +    }
хороший setUp метод, дулает все необходимые установки перед тестами

2024-03-03 20:35 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +        assertEquals(ownerBookings.size(), 1);
можно было бы так же проверить пару полей в возвращенном списке

аналагично в др местах

2024-03-03 20:35 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/users/UserControllerTest.java
> +        verify(userService, times(1)).getUserDto(userId);
я бы в проверке метода get ожидал бы проверку контента, который возвращается, а не просто вызов этого метода

2024-03-03 20:35 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +package ru.practicum.shareit.booking;
что бы в тестах лучше ориентироваться, так же стоит придерживаться той же иерархии пакетов, что и в основной части приложения

2024-03-03 20:35 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/users/UserServiceImplTest.java
> +}
добавь для UserRepository тест на findByEmail

2024-03-04 16:31 UTC, soursager commented on src/main/java/ru/practicum/shareit/validator/BookingValidator.java
> +public class BookingValidator {
Изменил наименование валидаторов

2024-03-04 16:34 UTC, soursager commented on src/main/java/ru/practicum/shareit/validator/BookingValidator.java
> +    public BookingDto validateAndReturnsBookingDto(long bookingId) {
Изменил наименования методов в валидаторе

2024-03-04 16:55 UTC, soursager commented on src/main/java/ru/practicum/shareit/validator/BookingValidator.java
> +                        " не существует!"));
Изменил все валидаторы, вынес в отдельные методы дублирование кода.

2024-03-04 17:02 UTC, soursager commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    PageValidator pageableValidator;
Добавил приватность всех полей во всех тестах

2024-03-04 17:02 UTC, soursager commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +    }
Спасибо!

2024-03-04 18:17 UTC, soursager commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +        assertEquals(ownerBookings.size(), 1);
Добавил во  всех тестах репозитория дополнительно проверку  по полям.

2024-03-04 19:24 UTC, soursager commented on src/test/java/ru/practicum/shareit/users/UserServiceImplTest.java
> +}
Добавил класс с двумя тестами на поиск. При удачном и при неудачном(пустом). Не стал выводить ошибки,чтобы была возможность видеть пустую страницу, думаю так логичнее.

2024-03-04 19:25 UTC, soursager commented on src/test/java/ru/practicum/shareit/users/UserControllerTest.java
> +        verify(userService, times(1)).getUserDto(userId);
Добавил проверку на возвращаемые элементы и поля.

2024-03-04 19:37 UTC, soursager commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +package ru.practicum.shareit.booking;
Изменил иерархию, сделал как в основном приложении.

2024-03-05 18:57 UTC, Fleaman777 approved these changes

2024-03-05 19:17 UTC, merged