Добавить запуск от Docker и Compose
soursager/java-shareit pull request #4
Opened 2024-03-17 14:51 UTC by soursager

2024-03-18 19:40 UTC, Fleaman777 requested changes

2024-03-18 19:40 UTC, Fleaman777 commented on docker-compose.yml
> +    image: postgres:16-alpine
хорошо, что указываешь конкретную версию имеджа, а не просто latest,
так безопасней, т.к. меньше шансов нарваться на версию базового имеджа, с которым текущая версия приложения не будет работать,
то же относится и к Dockerfile

2024-03-18 19:40 UTC, Fleaman777 commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +        return get("/owner?state={state}&from={from}&size={size}", userId, parameters);
подобные пути тоже хорошо бы выносить в константы, а то и вообще в пропертис, так будет ими удобней управлять в одном предноначенном для этого месте

2024-03-18 19:40 UTC, Fleaman777 commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                             @RequestHeader(USER_ID) Long userId, @RequestParam String approved) {
String approved - почему бы сразу не сделать тип boolean, что бы было удобней этой переменной дальше манипулировать

2024-03-18 19:40 UTC, Fleaman777 commented on server/src/main/resources/application.properties
> +spring.datasource.username=postgres
сейчас получается, что значение переменной окружения, используются то, которое указано в application.properties, а не то, которые в docker-compose
например в application.properties ,
можно использовать такую конструкцию: spring.datasource.username=${POSTGRES_USER:postgres}
она означает, что если, в докер-компосе не просетать переменную POSTGRES_USER, то будет использоваться дефлотное значение postgres

2024-03-18 19:50 UTC, soursager commented on server/src/main/resources/application.properties
> +spring.datasource.username=postgres
У меня падало приложение локально когда запускал и тестил, поэтому и оставил четкое определение. Скорее всего при запуске compose замена происходит корректно и тесты падать не должны, попробую.

2024-03-18 19:52 UTC, soursager commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                             @RequestHeader(USER_ID) Long userId, @RequestParam String approved) {
Здесь оставил так же, как и в основном приложении, т. к. Пользователь может ввести что-то иное, чем true и false, поэтому хотел пробрасывать ошибки. Разве так не логичнее?

2024-03-19 23:33 UTC, soursager commented on server/src/main/resources/application.properties
> +spring.datasource.username=postgres
Спасибо за рекомендацию про дефолтное значение, иначе не запускались локальные тесты, но на будущее понимаю,что эти поля необходимо закрывать.

2024-03-19 23:35 UTC, soursager commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +        return get("/owner?state={state}&from={from}&size={size}", userId, parameters);
Сделал поля приватные, но так же понимаю,что лучше выносить их в настройки. Но думаю, что нагляднее будет видно их в классе,чтобы не прыгать по строкам, так сказать "все рядом".

2024-03-20 06:29 UTC, Fleaman777 approved these changes

2024-03-20 06:43 UTC, merged